name: Build and Publish Package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@master

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -U setuptools twine
          python .github/scripts/update_release_version.py ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Build the package
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      # Publish the package to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
