# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
     - '*'

permissions:
  contents: read

jobs:
  build-n-publish:
    name: Build and publish to PyPi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: >-
        python -m pip install --upgrade pip
        pip install wheel
        pip install build
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d -f 3)
    - name: Update version in setup.py
      run: >-
        sed -i "s/{{VERSION_PLACEHOLDER}}/${{steps.tag.outputs.TAG_NAME}}/g" setup.py
    - name: Build package and Binary Wheel
      run: python setup.py sdist bdist bdist_wheel
    - name: Publish package
      if: startsWith(github.ref, 'ref/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        repository_url: https://pypi.org/project/pycurtain/
        password: ${{ secrets.PYPI_API_TOKEN }}
